name: dart_gestures
description: Dart gestures is a multi-touch gesture package built with dart that supports various prebuilt multi-touch actions
version: 0.1.0
author: cpuccino
homepage: https://github.com/cpuccino/dart_gestures
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0